### ISSUE TITLE
OpenSSL Error

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework-files#106]
> Warning:
 fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/demo.joomlatools.box/code/libraries/joomlatools-components/files/adapter/file.php on line 444

See https://github.com/joomlatools/demo.joomlatools.com/issues/248

I suggest to disable peer certification verification on dev instances, see https://www.php.net/manual/en/migration56.openssl.php

**Comment by jebbdomingo** [comment]
@yiendos are we still experiencing this in the demo?

**Comment by yiendos** [comment]
@jebbdomingo grr had to rebuild my box, it was running another version. I can confirm this bug still exists: 
<img width="1248" alt="Screenshot 2020-03-30 at 11 04 47" src="https://user-images.githubusercontent.com/3769817/77900859-91708800-7276-11ea-841c-4d0a6c06e2b5.png">

This is most probably due to the self signed certificates on our local boxes. If you need any help setting up the local demo site. Please let me know.

**Comment by johanjanssens** [comment]
@jebbdomingo @yiendos  Would this solve it: https://www.joomlatools.com/developer/tools/vagrant/faq/#how-can-i-get-rid-of-the-ssl-warnings ?

If not instead of checking for localhost, I would be checking to see if we are running inside the box and disable it then. There is an env var called JOOMLATOOLS_BOX you can check against. 

See: https://github.com/joomlatools/demo.joomlatools.com/blob/cb9e4e80e143c5bb534626f3738cae1904bd2770/code/libraries/joomlatools/component/koowa/exception/handler.php#L47

**Comment by yiendos** [comment]
@johanjanssens hmm the ssl is added to keychain and is trusted by the browser, so I think we are good from this point of view
<img width="1302" alt="Screenshot 2020-03-31 at 10 32 59" src="https://user-images.githubusercontent.com/3769817/78011203-2f2d8b00-733b-11ea-96dc-7a82667f02bc.png">

**Comment by yiendos** [comment]
@johanjanssens the demo box runs on the timble infrastructure code base, we've not created an environment variable: 

<img width="896" alt="Screenshot 2020-03-31 at 10 38 41" src="https://user-images.githubusercontent.com/3769817/78011734-e1655280-733b-11ea-8701-86d2f350f3e6.png">

Where as `JOOMLATOOLS_BOX` only exists on the `joomlatools-vagrant` box, we could most certainly create you an variable you wished. Let me know if this would help at all.

**Comment by johanjanssens** [comment]
@yiendos This issue is probably related to this: https://github.com/joomlatools/joomlatools-vagrant/issues/177
