### ISSUE TITLE
Route thumbnails

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework-files#48]
Route thumbnails links through application instead of direct linking.

Investigate performance impact with this change.

**Comment by johanjanssens** [comment]
@amazeika Doing this will require proper caching headers to be set on the images. This ensure that we do not receive a request each time the image is requested. It does allow us control over the images headers, which otherwise wouldn't be the case.

Various techniques can be used. 

- Append a param to the url so that we can generate a new unique link for the image, if the image changes.
- Use modified headers
- Use expire headers (less ideal).

**Comment by amazeika** [comment]
@johanjanssens I agree, thanks for the pointers :)

**Comment by amazeika** [comment]
Marking as invalid. We don't want to pursue this road due to performance concerns.
